name: Setup Python with uv
description: Install uv and cache dependencies
inputs:
  python-version:
    description: Python version to use (optional, for matrix builds)
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Cache uv dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          .venv
        key: uv-${{ runner.os }}-${{ inputs.python-version || 'default' }}-${{ hashFiles('**/pyproject.toml', '**/uv.lock') }}
        restore-keys: |
          uv-${{ runner.os }}-${{ inputs.python-version || 'default' }}-
          uv-${{ runner.os }}-

    - name: Install Python (uv-managed)
      if: ${{ inputs.python-version != '' }}
      shell: bash
      run: uv python install ${{ inputs.python-version }}
